version: "3.9"

services:
  # Backend Flask
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flask_app
    env_file: /backend/.env
    depends_on:
      - mongo
    expose:
      - "5000"
    # Si quieres seguir accediendo directo al backend desde tu máquina:
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app

  # Base de datos MongoDB
  mongo:
    image: mongo:6
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Frontend React + Nginx
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_app
    depends_on:
      - web
    ports:
      - "80:80"
    # Si quieres hot-reload con Vite desde host, esto sería otro rollo;
    # aquí asumimos build de producción.

volumes:
  mongo_data:
